### ISSUE TITLE
More explanations for Motion value

### ISSUE THREAD

**Issue by weijiawu** [CiaraStrawberry/svd-temporal-controlnet#6]
Thank you to the author for providing such a great open-source code!

when i try to train the code, I don't quite understand what specific values are stored in "average_motion.txt." Could you provide more explanation to help me successfully run the training code?

**Comment by CiaraStrawberry** [comment]
Hi! For this i used a dataset where the motion values were in .txt files of the same name as the image folders in a folder, so you'll want to read your average_motion.txt at the start and just poll the dict you've created for the relevant motion value all in dataset.py to train yours.

Also i miiight be breaking past compatibility by setting up a frame input toggle over the next few days so if you're gonna throw  a load of money training it, you may be best placed waiting until i do that.

**Comment by weijiawu** [comment]
Thank you for the rapid reply. Looking forward to the latest updates!

**Comment by pokameng** [comment]
@CiaraStrawberry 
hi  can you provide more information about motion_values_file?
thanks
